const actionType = {
  SAVE_COURSE: 'SAVE_COURSE',
  UPDATE_COURSE: 'UPDATE_COURSE',
  DELETE_COURSE: 'DELETE_COURSE',
  LOAD_ALL_COURSES: 'LOAD_ALL_COURSES',
  GET_COURSE_BY_ID: 'GET_COURSE_BY_ID',

  LOAD_ALL_AUTHORS: 'LOAD_ALL_AUTHORS'
};

export default actionType;